name: Update Packages

on:
    workflow_call:
        # inputs:
            # client_payload:
            #     package_name: ${{ github.event.client_payload.package_name }}
            #         type: string
            #     package_version: ${{ github.event.client_payload.package_version }}
            #     target_branch: ${{ github.event.client_payload.target_branch }}

jobs:
    pre:
        runs-on: ubuntu-latest

        steps:

            - name: show event payload
              run: echo ${{ github.event.client_payload.package_name }}, ${{ github.event.client_payload.package_version }}, ${{ github.event.client_payload.target_branch }}
           