on: workflow_call

jobs:
  setup_node:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v3

      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version: "20"

      - run: pnpm install
